name: Build Wheel

on:
  push:
    tags:
      - "v*" # Trigger on tag pushes that start with "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Choose a suitable version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools build

    - name: Build wheel
      run: |
        python -m build --wheel

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}